### ISSUE TITLE
반응형 페이지 구현

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#11]
### ISSUE
* Group: client
* Type: feature
* Detail: 반응형 페이지 구현

### TODO
- [x] md 화면 크기에 따라 페이지 구성 변경
- [x] sm 화면 크기에 따라 페이지 구성 변경
- [x] 모바일 화면 크기에 따라 페이지 구성 변경
- [x] sm, 모바일 화면이면 navBar 다르게 구현

### Estimated time
Pick one
```3h```
