### ISSUE TITLE
애니메이션 처리

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#13]
### ISSUE
* Group: client
* Type: feature
* Detail: 이미지, 텍스트 애니메이션 처리

### TODO
- [x] Intersection Observer custom hook 만들기
- [x] Animation custom hook 만들기
- [ ] Lotus 페이지 text 타이핑 효과, 페이드인 아웃
- [x] About 페이지 애니메이션
- [x] Skills 페이지 애니메이션
- [x] Project 페이지 애니메이션
- [x] project -> detail page 애니메이션
- [x] contact 페이지 애니메이션

### Estimated time
Pick one
```3h```
