### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#18]
### ISSUE
* Group: client
* Type: feature
* Detail: 추가적으로 수정이 필요한 부분 수정

### TODO
Lotus page
- [ ] 로투스 페이지 이미지 넣기
- [x] Learn More 애니메이션

Header
 - [x] 다크 모드 호버시 scale
 - [x] 버튼 hover시 애니메이션
 - [x] 다크모드 이미지 반대로 사용하기

About page
- [x]  About page 여백 조정

Skill page
- [x] skillCard 가운데 오도록 배치

Detail page
- [x] 반응형 디테일 페이지도 했는지 확인하기 (버튼 완료, Detail 내용은 내용 적은 이후 확인)
- [x] 모달뜨면 스크롤 전 페이지 스크롤과 관련없게 만들기 / close 누르면 이전에 봤던 위치 그대로

Project page
- [x] project 위아래 배치 사이즈 조절
- [x] project sm, mobile size일 때 translateX, width 설정

Contact page
- [x] mobile 사이즈 일때 contact card 가운데 배치

<br/>
<br/>

- [x] MoveToTop Btn hover시 효과 설정
- [x]  subtitle 밑의 여백 통일하기
- [ ]  subtitle 컴포넌트로 만들기
- [x] 카카오톡 url 공유시 정보 추가
- [x]  이미지 alt 속성 넣기
- [ ] 페이지 처음 들어갈 때 font 적용안될 때 로딩처리 하기
- [x] 390px이하일때 경고 화면 띄우기
- [x] 사이트 아이콘 넣기
- [x] map 메서드 이용시 빠뜨린 key 추가하기
- [x] 다른 영역에도 가로스크롤이 되는 경우 없애기 ⇒ overflow-x-hidden
- [x] small 사이즈일 때 제목 크기 통일시키기
- [x] 사용하지 않는 font 지우기
- [ ] 사용하지 않는 라이브러리 삭제

### Estimated time
Pick one
```5h```
