### ISSUE TITLE
2차 수정사항

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#31]
### ISSUE
* Group: client
* Type: feat
* Detail: 최종적으로 보안할 점을 체크

### TODO
- [x] 로투스 페이지 이미지 적용
- [x] Card hover시 scale
- [x] Card shoadow 적용
- [x] 다크모드 이미지 다시 변경
- [x] 불필요한 파일 삭제
- [x] 사용하지 않는 라이브러리 삭제
- [x] 로딩페이지 만들기

### Estimated time
Pick one
```3h```
