### ISSUE TITLE
ABOUT 페이지 구현

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#4]
### ISSUE
* Group: client
* Type: feature
* Detail: ABOUT 페이지 구현

### TODO
- [x] 3개의 full page 사용
- [x] 관련 내용 배치
  - [x] 소개글
  - [x] 학력, 경험, 자격증
  - [x] 스터디 
    - [x] 스터디 카드 클릭 시 외부 링크로 이동

### Estimated time
Pick one
```2h```
