### ISSUE TITLE
공통 컴포넌트 구현

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#5]
### ISSUE
* Group: client
* Type: feature
* Detail: 공통 컴포넌트 구현

### TODO
- [x] 클릭 시 맨 위로 가는 버튼
- [x] 다크모드 버튼
- [x] about 페이지 소개글
- [x] about 페이지 학력, 경험 템플릿
- [x] study 카드
- [x] skill 카드
- [x] team, solo tag
- [x] project 페이지 기술 스택 tag
- [x] project 페이지 설명 템플릿
- [x] project click 버튼
- [x] project 카드
- [x] close 버튼
- [x] contanct 카드
