### ISSUE TITLE
PROJECT 페이지 구현

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#7]
### ISSUE
* Group: client
* Type: feature
* Detail: project 페이지 구현

### TODO
- [x] 스크롤을 내릴 시 프로젝트들이 옆으로 넘어가게 구현
- [x] 프로젝트 카드 hover 애니메이션
- [x] Project page 구조잡기

### Estimated time
Pick one
```5h```
