### ISSUE TITLE
DETAIL 1차 모달 구현

### ISSUE THREAD

**Issue by chaelotus** [chaelotus/Lotus-Portfolio#8]
### ISSUE
* Group: client
* Type: feature
* Detail: detail page 구현

### TODO
- [x] 모달 형식으로 구성(전체화면으로, 위로 올라오는 듯이)
- [x] projectCard, projectCard > Click 버튼 누르면 모달이 뜨게끔 구현
- [x] close 버튼 누르면 닫힘

### Estimated time
Pick one
```3h```
